[package]
name = "goblin-camp"
version = "0.22.0"
authors = [
    "Ilkka Halila <gencontain@gmail.com>",
    "Alexander Krivács Schrøder <alexschrod@gmail.com>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
